# run: conda env create --file environment.yml
name: shcl-env

dependencies:
    - ipython
    - numpy>=1.12
    - seaborn>=0.7
    - scipy>=0.18.0
    - matplotlib>=2.0.0
    - Cython>=0.26
    - scikit-learn>=0.19.0
    - joblib>=0.11
